changelog:
  exclude:
    authors:
      - dependabot
      - pre-commit-ci
  categories:
    - title: Correction de bugs 🐛
      labels:
        - bug
    - title: Améliorations et nouvelles fonctionnalités 🎉
      labels:
        - enhancement
    - title: Amélioration de la qualité
      labels:
        - quality
    - title: Outillage 🔧
      labels:
        - tooling
    - title: Documentation 📖
      labels:
        - documentation
    - title: Divers
      labels:
        - "*"
